# Generated by Django 5.0.1 on 2024-02-16 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questionbank_remove_option_question_delete_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(max_length=50)),
                ('answer_2', models.CharField(max_length=50)),
                ('answer_3', models.CharField(max_length=50)),
                ('answer_4', models.CharField(max_length=50)),
                ('answer_5', models.CharField(max_length=50)),
                ('answer_6', models.CharField(max_length=50)),
                ('answer_7', models.CharField(max_length=50)),
                ('answer_8', models.CharField(max_length=50)),
                ('answer_9', models.CharField(max_length=50)),
                ('answer_10', models.CharField(max_length=50)),
                ('answer_11', models.CharField(max_length=50)),
                ('answer_12', models.CharField(max_length=50)),
                ('answer_13', models.CharField(max_length=50)),
                ('answer_14', models.CharField(max_length=50)),
                ('answer_15', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
