# Generated by Django 5.0.1 on 2024-02-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userresponse_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='field',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='response',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
