# Generated by Django 5.0.1 on 2024-02-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_userresponse_field_userresponse_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='response',
        ),
    ]
