# Generated by Django 5.0.1 on 2024-02-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_userresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='output',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
