# Generated by Django 4.2.9 on 2024-03-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_userresponse_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='artsque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=64, verbose_name='Option A')),
                ('option_2', models.CharField(max_length=64, verbose_name='Option B')),
                ('option_3', models.CharField(max_length=64, verbose_name='Option C')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='commerceque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=64, verbose_name='Option A')),
                ('option_2', models.CharField(max_length=64, verbose_name='Option B')),
                ('option_3', models.CharField(max_length=64, verbose_name='Option C')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='scienceque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=64, verbose_name='Option A')),
                ('option_2', models.CharField(max_length=64, verbose_name='Option B')),
                ('option_3', models.CharField(max_length=64, verbose_name='Option C')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
    ]
