# Generated by Django 4.2.10 on 2024-04-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_artsque_commerceque_scienceque'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityQues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=64, verbose_name='Option A')),
                ('option_2', models.CharField(max_length=64, verbose_name='Option B')),
                ('option_3', models.CharField(max_length=64, verbose_name='Option C')),
            ],
        ),
    ]
